# Generated by Django 5.2.17 on 2026-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Plot', 'Plot'), ('Commercial', 'Commercial'), ('Farm House', 'Farm House'), ('Shop', 'Shop'), ('Office', 'Office')], default='House', max_length=30)),
                ('purpose', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], default='Sale', max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, help_text='Property area in square feet.', max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
