# Generated by Django 5.2.17 on 2026-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_agentinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
